### ISSUE TITLE
Missing CSS file in NPM package for version 1.1.0

### ISSUE THREAD

**Issue by chrisgacsal** [aldi/bulma-social#4]
Hey Aldi,

First of all thanks for this project! 🙏 

I noticed that the `bin` directory including the `bulma-social.min.css` is completely missing when installing the latest version (`1.1.0`) from NPM.
I guess the following line in `.npmignore` causes the issue: https://github.com/aldi/bulma-social/blob/1.1.0/.npmignore#L3.
Could you please take a look on this matter and republish the package?

Many thanks! 🙏

**Comment by aldi** [comment]
Hello Chris,
Great catch! Thanks for letting me know. 👍
Just fixed it in my latest release. ([v1.1.1](https://github.com/aldi/bulma-social/releases/tag/1.1.1))
