### ISSUE TITLE
why no google sign in button?

### ISSUE THREAD

**Issue by jiangts** [aldi/bulma-social#8]

**Comment by aldi** [comment]
The Google sign-in button  was not compliant with the Google sign-in branding guidelines.
More information here: [https://developers.google.com/identity/branding-guidelines](url)

<img width="918" alt="Screenshot 2020-11-13 at 12 01 04" src="https://user-images.githubusercontent.com/15065804/99059998-0dbaa000-25a8-11eb-8260-df37964cc692.png">
